//<auto-generated>
#region License
//-----------------------------------------------------------------------
// <copyright>
//     Copyright matatabi-ux 2014.
// </copyright>
//-----------------------------------------------------------------------
#endregion

namespace ResponsiveGridSample.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;
    using System.Threading.Tasks;

    /// <summary>
    /// トップ画面の ViewModel のインタフェース
    /// </summary>
    public partial interface ITopPageViewModel
    {
        ObservableCollection<ItemContainerViewModel> Items { get; set; }
        double HorizontalScrollOffset { get; set; }
    }

    /// <summary>
    /// トップ画面の ViewModel
    /// </summary>
    
    public partial class TopPageViewModel : ViewModelBase, ITopPageViewModel
    {
        #region Items:写真情報 プロパティ
        /// <summary>
        /// 写真情報
        /// </summary>
        private ObservableCollection<ItemContainerViewModel> items; 

        /// <summary>
        /// 写真情報 の変更前の処理
        /// </summary>
        partial void OnItemsChanging(ref ObservableCollection<ItemContainerViewModel> value);

        /// <summary>
        /// 写真情報 の変更後の処理
        /// </summary>
        partial void OnItemsChanged();

        /// <summary>
        /// 写真情報 の取得および設定
        /// </summary>
        [RestorableData]
        public ObservableCollection<ItemContainerViewModel> Items
        {
            get
            {
                return this.items;
            }

            set
            {
                if (this.items != value)
                {
                    this.OnItemsChanging(ref value);
                    this.SetProperty<ObservableCollection<ItemContainerViewModel>>(ref this.items, value);
                    this.OnItemsChanged();
                }
            }
        }
        #endregion //Items:写真情報 プロパティ

        #region HorizontalScrollOffset:水平スクロール位置 プロパティ
        /// <summary>
        /// 水平スクロール位置
        /// </summary>
        private double horizontalScrollOffset; 

        /// <summary>
        /// 水平スクロール位置 の変更前の処理
        /// </summary>
        partial void OnHorizontalScrollOffsetChanging(ref double value);

        /// <summary>
        /// 水平スクロール位置 の変更後の処理
        /// </summary>
        partial void OnHorizontalScrollOffsetChanged();

        /// <summary>
        /// 水平スクロール位置 の取得および設定
        /// </summary>
        [RestorableData]
        public double HorizontalScrollOffset
        {
            get
            {
                return this.horizontalScrollOffset;
            }

            set
            {
                if (this.horizontalScrollOffset != value)
                {
                    this.OnHorizontalScrollOffsetChanging(ref value);
                    this.SetProperty<double>(ref this.horizontalScrollOffset, value);
                    this.OnHorizontalScrollOffsetChanged();
                }
            }
        }
        #endregion //HorizontalScrollOffset:水平スクロール位置 プロパティ

    }

}